name: CI — Gate

on:
  pull_request:
    paths-ignore:
      - "fileflows/**"
      - "mineru/**"

jobs:
  status:
    runs-on: actions-runners-containers
    name: Build Success
    steps:
      - run: echo "All jobs passed or skipped"
