name: Build & Push — Fileflows

on:
  push:
    branches: [main]
    paths:
      - "fileflows/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      container: "fileflows"
      push: true
    secrets: inherit
