name: CI — Fileflows

on:
  pull_request:
    paths:
      - "fileflows/**"
  push:
    branches-ignore: [main]
    paths:
      - "fileflows/**"
      - ".github/workflows/**"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      container: "fileflows"
      push: false
    secrets: inherit
