name: Build Mineru Container

on:
  push:
    branches: [main]
    paths:
      - "mineru/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      container: "mineru"
      push: true
    secrets: inherit
