name: CI — Mineru

on:
  pull_request:
    paths:
      - "mineru/**"
      - ".github/workflows/**"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      container: "mineru"
      push: false
    secrets: inherit
