name: CI — Mineru

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "mineru/**"
  push:
    branches-ignore: [main]
    paths:
      - "mineru/**"
      - ".github/workflows/**"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      container: "mineru"
      push: false
    secrets: inherit
