name: CI — Mineru

on:
  pull_request:
    paths:
      - "mineru/**"
      - ".github/workflows/**"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      container: "mineru"
      push: false
    secrets: inherit

  status:
    runs-on: actions-runners-containers
    if: ${{ !cancelled() }}
    name: Build Success
    needs:
      - build
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: All jobs passed or skipped?
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: echo "All jobs passed or skipped"
