name: Build Mineru Container

permissions:
  contents: write
  packages: write

on:
  push:
    branches: [main]
    paths:
      - "mineru/**"
      - ".github/workflows/**"
  workflow_dispatch:

concurrency:
  group: build-mineru
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      container: "mineru"
      push: true
    secrets: inherit
